# Trabajo integrador - Parte 1
## Python y Numpy

**Nombre**: Víctor David Silva

In [5]:
import numpy as np

## Ejercicio 1

Dada una matriz en formato *numpy array*, donde cada fila de la matriz representa un vector matemático, se requiere computar las normas $l_0$, $l_1$, $l_2$, $l_{\infty}$, según la siguientes definiciones:

\begin{equation}
    ||\mathbf{x}||^{p} = \bigg(\sum_{j=1}^{n}{|x_i|^p}\bigg)^{\frac{1}{p}}
\end{equation}

con los casos especiales para $p=0$ y $p=\infty$ siendo:

\begin{equation}
    \begin{array}{rcl}
        ||\mathbf{x}||_0 & = & \bigg(\sum_{j=1 \wedge x_j != 0}{|x_i|}\bigg)\\
        ||\mathbf{x}||_{\infty} & = & \max_{i}{|x_i|}\\
    \end{array}
\end{equation}

In [6]:

def normas_matriz(matriz):
    norma_l0 = np.sum(matriz > 0, axis=1)
    norma_l1 = np.sum(np.abs(matriz), axis=1)
    norma_l2 = np.sqrt(np.sum(matriz ** 2, axis=1))
    norma_linf = np.max(matriz, axis=1)
    return norma_l0, norma_l1, norma_l2, norma_linf

A = np.matrix([[1, 2], [3, 4]])
 
vector_norma_l0, vector_norma_l1, vector_norma_l2, vector_norma_linf = normas_matriz(A)

print('Para la matriz: \n', A)
print('Vector norma l_0: \n', vector_norma_l0)
print('Vector norma l_1: \n', vector_norma_l1)
print('Vector norma l_2: \n', vector_norma_l2)
print('Vector norma l_infinita: \n', vector_norma_linf)


Para la matriz: 
 [[1 2]
 [3 4]]
Vector norma l_0: 
 [[2]
 [2]]
Vector norma l_1: 
 [[3]
 [7]]
Vector norma l_2: 
 [[4.12310563]
 [6.08276253]]
Vector norma l_infinita: 
 [[2]
 [4]]


## Ejercicio 2

En clasificación contamos con dos arreglos, la “verdad” y la “predicción”. Cada elemento de los arreglos pueden tomar dos valores, “True” (representado por 1) y “False” (representado por 0). Entonces podemos definir 4 variables:

* True Positive (TP): El valor verdadero es 1 y el valor predicho es 1
* True Negative (TN): El valor verdadero es 0 y el valor predicho es 0
* False Positive (FP): El valor verdadero es 0 y el valor predicho es 1
* False Negative (FN): El valor verdadero es 1 y el valor predicho es 0

A partir de esto definimos:

* Precision = TP / (TP + FP)
* Recall = TP / (TP + FN)
* Accuracy = (TP + TN) / (TP + TN + FP + FN)
 
Calcular las 3 métricas con Numpy y operaciones vectorizadas.

In [7]:

truth =      np.array([1,1,0,1,1,1,0,0,0,1])
prediction = np.array([1,1,1,1,0,0,1,1,0,0])

#TP = TN, FP, FN = 0
TP = ((truth==1) & (prediction==1)).sum()
TN = ((truth==0) & (prediction==0)).sum()
FP = ((truth==0) & (prediction==1)).sum()
FN = ((truth==1) & (prediction==0)).sum()

precision = TP/(TP+FP)
recall = TP / (TP + FN)
accuracy = (TP + TN) / (TP + TN + FP + FN)

print('precision:',precision)
print('recall:',recall)
print('accuracy:',accuracy)


precision: 0.5
recall: 0.5
accuracy: 0.4


## Ejercicio 3

Crear una función que separe los datos en train-validation-test. Debe recibir de parametros:

- X: Array o Dataframe que contiene los datos de entrada del sistema.
- y: Array o Dataframe que contiene la(s) variable(s) target del problema.
- train_percentage: _float_ el porcentaje de training.
- test_percentage: _float_ el porcentaje de testing.
- val_percentage: _float_ el porcentaje de validación.
- shuffle: _bool_ determina si el split debe hacerse de manera random o no.

Hints: 

* Usar Indexing y slicing
* Usar np.random.[...]

In [8]:
import numpy as np

def split(X, y, train_percentage, val_percentage, test_percentage, shuffle):
      N = len(X)
      if(shuffle):
            index = np.random.permutation(N) 
      else:
            index = np.arange(N)
      train_N = int(N * train_percentage)
      val_N = int(N * val_percentage)
      test_N = int(N * test_percentage)
      train_index = index[:train_N]
      val_index = index[(train_N):(train_N+val_N)]
      test_index = index[-test_N:]
      return X[train_index], y[train_index], X[val_index], y[val_index], X[test_index], y[test_index]


n = 60
X = np.arange(0,n)
y = np.arange(0,n)

X_train, y_train, X_val, y_val, X_test, y_test = split(X,y,0.7,0.15,0.15,True)

print('Los valores de X-train son: \n', X_train)
print('Los valores de X-val son: \n', X_val)
print('Los valores de X-test son: \n', X_test)
print('\nLos valores de y-train son: \n', y_train)
print('Los valores de y-val son: \n', y_val)
print('Los valores de y-test son: \n', y_test)

Los valores de X-train son: 
 [40 42  2 37 57 44 20 46 12 47 25 13 30 17  4 10 34 23 54 51 59  9 16 35
 50 24  5 36 18 31  0 27 49 19 52 29  8  6 15 32  3  1]
Los valores de X-val son: 
 [22 41 45 14 11 48 56 38 55]
Los valores de X-test son: 
 [21 43 58 39 26 28  7 33 53]

Los valores de y-train son: 
 [40 42  2 37 57 44 20 46 12 47 25 13 30 17  4 10 34 23 54 51 59  9 16 35
 50 24  5 36 18 31  0 27 49 19 52 29  8  6 15 32  3  1]
Los valores de y-val son: 
 [22 41 45 14 11 48 56 38 55]
Los valores de y-test son: 
 [21 43 58 39 26 28  7 33 53]
